### PR TITLE
Reimplementation of SDK

### PR DESCRIPTION
**Pull request by KineticCookie**
No CLI deps.
Pure SDK.

Implements #6, #8

### CODE REVIEW

**Comment by KineticCookie** [comment]
@trthhrtz, are we ready to merge to master?

**Comment by trthhrtz** [comment]
@KineticCookie give me 15-30 minutes to finish the Servable.create

**Comment by KineticCookie** [comment]
Sure, waiting for #21 then.

**Comment by trthhrtz** [comment]
@KineticCookie good to go!

**Pull request merged**
