### PR TITLE
(HYD-380) Support namedtuple in PredictorsModule

### PR DESCRIPTION
**Pull request by Valenzione**
I think it'd be great to support named tuples in predictors as they are the main type of objects produced during iteration on pandas Dataframes and hence play an important role in sending tabular data to Hydrosphere.

However, there is no such type as `namedtuple`, since `namedtuple()` is a factory method returns a new tuple subclass named `typename`.  There is no way to check it with `isinstance`, but we can check for callable attribute `_asdict` which is present in all namedtuples. 

I am not completely sure in this solution, wdy @KineticCookie @trthhrtz ? 

By doing so, we start supporting not only namedtuples, but all methods with `_asdict` function. 
We can add a check for having `tuple` class in bases to mitigate this.

### CODE REVIEW

**Comment by trthhrtz** [comment]
after closing this PR, please del feature/predictors_namedtuple_support branch

**Comment by trthhrtz** [comment]
As we don't use tuples, we could do a `isinstance(o, tuple)` check as namedtuple inherits from tuple.

If we need to diff between tuple and namedtuple I'd stick with this: https://stackoverflow.com/a/49325922/7127824

**Comment by Valenzione** [comment]
Okey, lets do so then
```def isinstance_namedtuple(x):                                                               
  return (isinstance(x, tuple) and                                                  
          isinstance(getattr(x, '__dict__', None), collections.Mapping) and         
          getattr(x, '_fields', None) is not None)       ```

**Comment by trthhrtz** [comment]
@Valenzione @KineticCookie , ready for review

**Comment by Valenzione** [comment]
👍 
Approve

**Comment by trthhrtz** [comment]
@Valenzione , following our slack discussion, I have added support of `<class 'pandas.core.frame.Pandas'>`. Now you can pass values without using `_asdict()`

**Comment by trthhrtz** [comment]
Closed because of the mess with merging branches (see https://github.com/Hydrospheredata/hydro-serving-sdk/pull/67)

**Pull request closed without merging**
